---
  - name:  copy cron script
    copy:
      src: "{{ role_path }}/files/clamcron"
      dest: /usr/clamav/scripts/clamcron.sh
      owner: root
      mode: 0755
    tags:
      - clamav

  - name: Setup cronjob for freshclam updates
    cron:
      job: /usr/bin/freshclam
      hour: 17
      minute: 0
      name: freshclam
    tags:
      - clamav

  - name: Setup cronjob for freshclam updates
    cron:
      job: /usr/clamav/scripts/clamcron.sh
      hour: 20
      minute: 0
      name: clamscan
    tags:
      - clamav
