---
  - name: Configure SELinux for clamav
    seboolean:
      name: "{{item}}"
      state: yes
      persistent: yes
    with_items:
      - antivirus_can_scan_system
      - antivirus_use_jit
    when: >
      clamav_selinux_check_result is defined and
      clamav_selinux_check_result.stdout.find('disabled') == -1
    tags:
      - clamav
